# Sugestões automáticas baseadas em sentimentos detectados

frases_negativo = [
    "Notamos um tom mais preocupado nas suas postagens de {dia_semana}, {nome_usuario}. Já pensou em fazer uma pausa para cuidar de você?",
    "Hoje parece ter sido um dia mais difícil. Que tal reservar um tempo para {atividade_recomendada} e aliviar a mente?",
    "Você demonstrou estar mais sensível nesta {dia_semana}, {nome_usuario}. Lembre-se: tudo bem não estar bem.",
    "Parece que o dia foi pesado. Um momento para respirar fundo e desacelerar pode fazer bem.",
    "Percebemos sentimentos mais negativos hoje. Já tentou escrever sobre isso com mais detalhes no seu diário?",
    "Talvez seja um bom dia para não se cobrar tanto. Seja gentil consigo mesmo(a), {nome_usuario}.",
    "As emoções de hoje estão mais carregadas. Uma caminhada ou ouvir música relaxante pode ajudar a aliviar.",
    "Seu texto indica ansiedade. Já pensou em técnicas de respiração ou meditação para se acalmar?",
    "Seu desabafo é válido. Se precisar, procure alguém de confiança para conversar e desabafar.",
    "Essa tensão emocional pode ser sinal de algo acumulado. Um tempo offline pode fazer diferença.",
    "Senti uma carga emocional intensa nesta {dia_semana}. Cuide-se com carinho e atenção.",
    "Sua escrita reflete tristeza. Que tal usar seu diário como espaço seguro para se expressar?",
    "É natural se sentir assim às vezes. Acolha esses sentimentos sem julgamentos, {nome_usuario}.",
    "Você parece sobrecarregado. Já tentou uma pausa digital por algumas horas para relaxar?",
    "Sinais de irritação são normais. Que tal fazer algo que normalmente te acalma?",
    "O padrão emocional desta {dia_semana} sugere frustração. Escrever pode ajudar a clarear seus pensamentos.",
    "Dias difíceis fazem parte. Não se isole — você não está sozinho(a), {nome_usuario}.",
    "Você se expressou de forma intensa. Que tal transformar essa emoção em arte ou música?",
    "Reconhecer seus sentimentos é um passo importante. Valorize essa consciência!",
    "Talvez seja o momento de buscar apoio emocional. Você merece todo cuidado, {nome_usuario}.",
    "Sugiro uma atividade calma hoje. Talvez um banho quente ou assistir a um filme leve?",
    "Você não precisa resolver tudo de uma vez. Um passo de cada vez já é suficiente.",
    "O conteúdo sugere dor emocional. Que tal reler algo que te faz bem e te conforta?",
    "Sinta-se à vontade para registrar mais sobre isso. É seguro se expressar aqui.",
    "Lembre-se: até os dias ruins têm fim. Você é mais forte do que imagina.",
    "Emoções negativas também ensinam. Reflita sobre o que pode aprender com isso.",
    "Se sentir para baixo faz parte da vida. Respire fundo e lembre-se que você vai superar isso.",
    "Pode ser um bom momento para conversar com alguém que você confia, {nome_usuario}.",
    "A tristeza é uma emoção legítima. Permita-se senti-la e acolhê-la com cuidado.",
    "Quando a mente pesa, cuidar do corpo pode ajudar. Experimente {atividade_recomendada}.",
    "Mesmo em dias difíceis, pequenos gestos de cuidado fazem a diferença.",
    "Que tal uma pausa para ouvir suas músicas favoritas e se reconectar consigo mesmo(a)?",
    "Está tudo bem pedir ajuda quando as emoções apertam, {nome_usuario}. Você não está só.",
    "Lembre-se de que sentir-se vulnerável é humano e faz parte do processo de cura.",
    "Sua jornada inclui altos e baixos, e cada passo importa. Seja paciente com você.",
    "Tente evitar cobranças excessivas hoje. Seu bem-estar é prioridade.",
    "Se sentir esgotado(a) é sinal para desacelerar. Que tal uma pausa para respirar?",
    "Seu corpo e mente merecem atenção especial nestes momentos. Cuide-se com carinho.",
    "Emoções negativas podem ser um sinal para cuidar mais de si mesmo(a).",
    "Que tal anotar o que está sentindo? Às vezes, colocar para fora ajuda a clarear.",
    "Não se esqueça: suas emoções são válidas, mesmo as difíceis.",
    "Você está passando por um momento desafiador. Dê tempo ao tempo, {nome_usuario}.",
    "Lembre-se de que a tempestade passa, e dias melhores virão.",
    "Permita-se descansar e cuidar da sua saúde emocional.",
    "Respire fundo e tente focar em pequenas coisas que trazem conforto.",
    "Não hesite em buscar apoio profissional, se sentir necessidade.",
    "Tente substituir pensamentos negativos por afirmações gentis consigo mesmo(a).",
    "Que tal tentar uma atividade relaxante, como a meditação ou uma caminhada?",
    "Você merece momentos de paz, mesmo em dias difíceis.",
    "Procure manter uma rotina que respeite seus limites e necessidades.",
    "Você não está sozinho(a) nessa jornada. Busque quem possa te apoiar.",
    "Se precisar, compartilhe seus sentimentos. Isso pode aliviar o peso emocional.",
    "Reconhecer o cansaço emocional é importante para a sua recuperação.",
    "Uma boa noite de sono pode ajudar a clarear a mente e melhorar o humor.",
    "Você está fazendo o melhor que pode. Valorize esse esforço.",
    "A paciência consigo mesmo(a) é um ato de amor e autocuidado.",
    "A tristeza não define quem você é. Ela é apenas um sentimento passageiro.",
    "Às vezes, o descanso é o melhor remédio para a mente cansada.",
    "Em momentos difíceis, busque coisas simples que tragam um pouco de alegria.",
    "Não se cobre tanto. É normal ter dias ruins, eles também passam.",
    "Procure fazer algo que você goste, mesmo que seja um pequeno gesto.",
    "Você pode transformar esses sentimentos em aprendizado e crescimento.",
    "Acolher suas emoções é o primeiro passo para superá-las.",
    "Lembre-se que você é capaz e que merece se sentir bem.",
    "O amor-próprio é fundamental para enfrentar as dificuldades.",
    "Pequenas conquistas diárias ajudam a construir uma mente mais forte.",
    "Sua jornada é única. Respeite seu ritmo e suas necessidades.",
    "Não se isole. O contato com pessoas queridas ajuda a aliviar a carga emocional.",
    "Está tudo bem pedir ajuda e dividir o peso das emoções.",
    "Mesmo em dias nublados, o sol está esperando para brilhar novamente.",
    "Use seu diário como um espaço seguro para expressar tudo que sente.",
    "Você é muito mais forte do que pensa. Continue caminhando.",
    "Lembre-se de que sua saúde mental é tão importante quanto a física.",
    "Procure focar no presente e nas coisas que você pode controlar agora.",
    "Respire com calma e repita para si mesmo(a): \"Eu estou fazendo o meu melhor\".",
    "Que tal tentar atividades criativas para aliviar o estresse, como pintura ou escrita?",
    "Permita-se momentos de silêncio para ouvir seu coração e suas necessidades.",
    "Você merece acolhimento, compreensão e tempo para se recuperar.",
    "Não se sinta culpado(a) por sentir tristeza ou ansiedade. É parte do ser humano.",
    "Você não está sozinho(a). Muitos enfrentam desafios parecidos e superam.",
    "Hoje pode ser um passo pequeno, mas importante na sua recuperação emocional.",
    "A paciência é uma virtude que se cultiva principalmente consigo mesmo(a).",
    "Busque a calma em pequenos momentos ao longo do dia.",
    "Permita-se sentir e respeitar suas emoções, mesmo as mais difíceis.",
    "Você merece uma vida equilibrada e momentos de tranquilidade.",
    "Lembre-se: pedir ajuda é um ato de coragem, não de fraqueza.",
    "Cuide de você com carinho, porque você merece todo amor do mundo."
]

frases_positivo = [
    "Notamos um tom mais alegre e leve nas suas postagens de {dia_semana}, {nome_usuario}. Que ótimo ver seu sorriso aqui!",
    "Parece que hoje foi um dia positivo para você. Continue assim e aproveite para fazer {atividade_recomendada}!",
    "Suas palavras refletem esperança e força nesta {dia_semana}. Continue se cuidando com carinho.",
    "É inspirador ver seu crescimento e otimismo. Que tal compartilhar essa energia com alguém querido?",
    "Sua escrita hoje traz muita luz e serenidade. Que tal aproveitar para praticar {atividade_recomendada}?",
    "Você demonstrou gratidão e alegria hoje. Continue cultivando esses sentimentos, {nome_usuario}.",
    "Que bom ver você superando desafios e celebrando pequenas vitórias!",
    "Seu texto indica confiança e coragem. Siga firme nesse caminho!",
    "A energia positiva das suas postagens ilumina quem está ao seu redor.",
    "Você tem feito progressos incríveis. Que tal registrar suas conquistas no diário?",
    "Sua mente está clara e focada hoje. Aproveite para fazer algo que goste muito.",
    "É maravilhoso ver seu comprometimento com o autocuidado e bem-estar.",
    "Você está mais resiliente e forte, {nome_usuario}. Isso é motivo de orgulho!",
    "Suas emoções refletem equilíbrio e paz. Que tal um momento para relaxar com {atividade_recomendada}?",
    "Sua expressão mostra que você está encontrando sua melhor versão.",
    "Continue valorizando seu tempo e cuidando da sua saúde emocional.",
    "Você está brilhando! Aproveite essa energia positiva e compartilhe-a com quem ama.",
    "Suas palavras inspiram calma e esperança. Que tal escrever uma carta para você mesmo(a)?",
    "Você está cultivando sentimentos positivos que fortalecem sua caminhada.",
    "Percebo um brilho especial nas suas postagens. Que tal celebrar com algo que gosta?",
    "Sua força interior está crescendo a cada dia. Continue acreditando em você!",
    "Você está mais aberto(a) para receber coisas boas. Que tal praticar {atividade_recomendada} para se manter assim?",
    "Sua jornada é repleta de superação e amor-próprio. Isso é admirável!",
    "Você tem motivos para sorrir. Que tal registrar seus momentos felizes no diário?",
    "Seus textos mostram clareza e motivação. Continue firme no seu caminho, {nome_usuario}.",
    "Sua energia positiva contagia a todos ao seu redor.",
    "Você está aprendendo a se valorizar cada vez mais. Isso é maravilhoso!",
    "É um prazer acompanhar seu progresso e suas conquistas.",
    "Seu olhar sobre a vida está mais leve e esperançoso. Que tal aproveitar para fazer {atividade_recomendada}?",
    "Continue acreditando no seu potencial e nos seus sonhos.",
    "Você está cuidando muito bem de si mesmo(a). Parabéns!",
    "Sua positividade hoje é um convite para celebrar a vida.",
    "Você merece toda felicidade que está encontrando.",
    "Sua escrita revela um coração cheio de esperança e luz.",
    "Aproveite essa fase positiva para se conectar com o que te faz bem.",
    "Você está se tornando uma versão cada vez melhor de si mesmo(a).",
    "Sua jornada inspira quem tem a sorte de acompanhá-la.",
    "Continue firme na busca por equilíbrio e bem-estar.",
    "Seu otimismo é uma força poderosa, {nome_usuario}. Continue assim!",
    "Você está encontrando motivos para agradecer a cada dia.",
    "Que tal aproveitar esse momento para praticar {atividade_recomendada} e aumentar sua felicidade?",
    "Você merece todos os momentos de paz e alegria que está vivenciando.",
    "Seu sorriso, mesmo que não visível, brilha nas suas palavras.",
    "Continue cultivando amor-próprio e autoconfiança.",
    "Você está mais leve e conectado(a) com suas emoções positivas.",
    "É incrível ver como você está evoluindo. Parabéns!",
    "Sua atitude positiva ajuda a construir um futuro mais feliz.",
    "Continue nutrindo sua mente e coração com bons pensamentos.",
    "Você está se fortalecendo a cada dia, e isso é lindo de ver.",
    "Sua jornada de autodescoberta está cheia de aprendizados valiosos.",
    "Continue caminhando com coragem e alegria.",
    "Você merece celebrar cada passo dado em direção ao seu bem-estar.",
    "Sua energia hoje é inspiradora. Que tal compartilhar essa luz com alguém?",
    "Você está crescendo e florescendo como merece.",
    "Continue buscando momentos que te tragam paz e felicidade.",
    "Sua resiliência é uma inspiração para todos ao seu redor.",
    "Que bom ver você cuidando tão bem de si mesmo(a), {nome_usuario}.",
    "Sua positividade é contagiante. Continue assim!",
    "Você está no caminho certo. Siga firme e confiante.",
    "É um prazer ver sua evolução pessoal e emocional.",
    "Você merece sentir essa alegria profunda todos os dias.",
    "Sua escrita hoje revela força e serenidade.",
    "Continue acreditando na sua capacidade de superar desafios.",
    "Que tal aproveitar essa energia positiva para se dedicar a {atividade_recomendada}?",
    "Você está fazendo um trabalho incrível cuidando de si.",
    "Sua jornada é cheia de luz e esperança. Continue brilhando!",
    "Parabéns por cada pequeno avanço, eles constroem o grande sucesso.",
    "Você é capaz de transformar seus dias em momentos felizes.",
    "Continue acreditando que o melhor ainda está por vir, {nome_usuario}.",
    "Sua escrita mostra que você está se conectando mais consigo mesmo(a).",
    "Que tal aproveitar essa energia para inspirar outras pessoas?",
    "Você merece todo amor e cuidado que está dedicando a si mesmo(a).",
    "Seu otimismo hoje é um sinal de que você está no caminho certo.",
    "Continue cultivando pensamentos que elevem seu espírito.",
    "Você está mais confiante e preparado(a) para enfrentar o que vier.",
    "Sua positividade é uma luz que ilumina seu caminho e o dos outros."
]

frases_neutro = [
    "Sua postagem de {dia_semana} está equilibrada. Que tal explorar como você está se sentindo mais a fundo?",
    "Você parece estável hoje. Um bom momento para refletir ou organizar ideias.",
    "Esse tom mais neutro pode indicar um dia calmo. Aproveite a serenidade!",
    "Parece que seu humor está regular hoje. Que tal planejar algo simples que te dá prazer?",
    "Postagens neutras também são importantes. Elas mostram consistência emocional.",
    "Sua escrita está centrada. Que tal manter esse equilíbrio com uma rotina leve?",
    "Um dia sem grandes altos ou baixos pode ser ótimo para autocuidado.",
    "Que tal usar esse momento de estabilidade para fazer algo construtivo?",
    "Postagens como a de hoje sugerem maturidade emocional. Parabéns!",
    "Sua neutralidade pode indicar introspecção. Já pensou em escrever mais profundamente sobre isso?",
    "Dias tranquilos também merecem ser registrados. Eles mostram estabilidade.",
    "Você está navegando o dia com serenidade. Continue assim!",
    "Sentimentos neutros são uma boa base. Tente identificar pequenas alegrias ao longo do dia.",
    "Percebemos constância nas emoções. Isso ajuda a criar bons hábitos.",
    "Sua energia hoje está leve. Um bom momento para algo criativo.",
    "Com equilíbrio, é mais fácil tomar decisões conscientes. Que tal usar isso a seu favor?",
    "O conteúdo parece reflexivo. Ótimo dia para organização ou leitura.",
    "Essa neutralidade pode ser útil para cuidar de tarefas pendentes com calma.",
    "Dias assim ajudam a recarregar as energias. Mantenha esse ritmo.",
    "Suas palavras mostram clareza. Continue escrevendo!",
    "Notamos um padrão tranquilo. Que tal fazer algo leve, como um passeio curto?",
    "Postagens equilibradas são essenciais para entender padrões emocionais.",
    "Esse conteúdo mostra uma pausa emocional. Aproveite para se conectar com você mesmo(a).",
    "Momentos neutros ajudam a regular emoções mais intensas. Use isso a seu favor.",
    "Seu texto mostra serenidade. Ideal para um planejamento tranquilo.",
    "Hoje parece um dia comum. Que tal fazer algo diferente para trazer um pouco de novidade?",
    "Você expressou estabilidade. Isso pode ser uma boa base para crescimento pessoal.",
    "A calmaria de hoje pode ser ideal para recarregar a mente.",
    "Mesmo dias neutros têm sua beleza. Você está presente no agora.",
    "Sua neutralidade traz espaço para introspecção. Que tal anotar seus pensamentos?",
    "Postar mesmo em dias estáveis mostra comprometimento com o autocuidado.",
    "Essa estabilidade é um sinal de amadurecimento emocional.",
    "Nada em excesso hoje — isso é uma forma de equilíbrio.",
    "A ausência de extremos pode ser um convite à atenção plena.",
    "Seu texto está calmo. Isso pode ser reconfortante para você e quem lê.",
    "Hoje parece ser um dia de pausa. Aproveite para respirar fundo.",
    "Postagens como a de hoje ajudam a mapear seus estados internos com clareza.",
    "Manter constância é um sinal de força interior.",
    "Esse tom revela controle emocional. Muito bem!",
    "Seu relato transmite paz. Continue nesse caminho.",
    "Você demonstrou calma. Que tal valorizar isso com uma atividade leve?",
    "Hoje foi um dia comum, mas não menos importante.",
    "Sua escrita revela serenidade. Um ótimo momento para um chá e reflexão.",
    "Você parece estar num ponto de equilíbrio. Cuide bem desse espaço.",
    "Esse estado emocional pode ser ideal para avaliar metas.",
    "A neutralidade pode ser um convite para observar os detalhes esquecidos.",
    "Seu registro mostra tranquilidade. Isso pode ser restaurador.",
    "Postagens assim indicam autoconhecimento em construção.",
    "Estar em paz consigo mesmo é um grande passo. Parabéns!",
    "Momentos neutros constroem a base para dias mais intensos.",
    "Essa serenidade pode abrir espaço para ideias novas.",
    "A simplicidade do dia pode trazer clareza interior.",
    "Seu equilíbrio hoje pode ser inspiração para os próximos dias.",
    "Você parece estar centrado. Mantenha esse foco.",
    "A regularidade emocional também precisa ser valorizada.",
    "Sua descrição é suave. Isso é acolhedor.",
    "Postagens assim são um lembrete de que tudo passa, inclusive o caos.",
    "Essa constância pode ser uma conquista. Reconheça seu progresso.",
    "Um dia sem turbulência também é um bom dia.",
    "Esse ritmo calmo pode ser ótimo para fazer algo por você.",
    "Sua escrita traz um senso de estabilidade. Continue explorando isso.",
    "Hoje foi um dia de neutralidade emocional. Há beleza nisso também.",
    "Você manteve o equilíbrio emocional. Isso é admirável.",
    "Esse tom calmo pode ser o que você precisava hoje.",
    "Seu dia foi sereno. Aproveite para cuidar de si com carinho.",
    "A neutralidade pode ser reflexo de um estado interno organizado.",
    "Essa calmaria pode ser sinal de evolução emocional.",
    "Postar em um dia tranquilo é sinal de comprometimento com o diário.",
    "Você se expressou de forma centrada. Isso mostra maturidade.",
    "Sentimentos suaves também são dignos de atenção.",
    "Seu texto hoje é como um lago calmo: profundo e silencioso.",
    "A ausência de emoção forte pode ser sinal de estabilidade interior.",
    "Seu registro sereno mostra que você está presente em si.",
    "Esse estado pode ser ideal para retomar pequenas metas.",
    "Você parece estar em sintonia com o agora.",
    "A calma de hoje é um presente. Agradeça por ela.",
    "Seu relato indica equilíbrio. Continue se cuidando.",
    "A leveza do dia pode ser uma pausa merecida.",
    "Essa escrita equilibrada reflete sua dedicação ao autoconhecimento.",
    "Você expressou neutralidade com clareza. Isso é importante.",
    "Estar bem com a própria companhia é algo valioso.",
    "Você está cultivando constância. Isso gera bons frutos.",
    "Essa escrita centrada pode ajudar outras pessoas também.",
    "A neutralidade de hoje talvez seja sinal de descanso emocional.",
    "Registrar um dia comum é uma forma de carinho consigo mesmo.",
    "Você construiu um espaço seguro nas palavras de hoje.",
    "A rotina emocional também ensina muito. Obrigado por compartilhar.",
    "Esse estado emocional pode ser fértil para ideias criativas.",
    "Postagens assim são como âncoras nos dias agitados.",
    "Sua serenidade é um sinal de força interna.",
    "Hoje parece ter sido tranquilo. Que bom poder reconhecer isso.",
    "Seu texto mostra que você está se ouvindo com mais atenção.",
    "Você está cultivando presença e paz. Isso é poderoso.",
    "Essa descrição serena pode te ajudar a descansar melhor hoje.",
    "Sua tranquilidade é um lembrete de que o equilíbrio é possível.",
    "Registrar a neutralidade é como observar o próprio centro.",
    "Esse relato é como uma pausa gentil entre emoções fortes.",
    "Você escreveu com calma. Isso se reflete nas suas palavras.",
    "Essa estabilidade é como um abraço interno.",
    "Sua neutralidade transmite sensatez. Que bom ver isso.",
    "Hoje foi um dia calmo, e isso também merece destaque.",
    "Sua constância mostra que você está se conhecendo melhor.",
    "Estar neutro é estar aberto ao que vier. Parabéns pela disposição.",
    "A leveza do seu texto reflete sua jornada emocional.",
    "Seu relato revela presença, mesmo sem grandes emoções.",
    "Esse estado emocional é terreno fértil para o autoconhecimento.",
    "Você demonstrou sensatez nas suas palavras de hoje. Continue assim."
]

atividade_recomendada = {
    "positivo": [
        "fazer uma caminhada ao ar livre",
        "compartilhar sua alegria com um amigo",
        "escrever sobre o que deixou seu dia especial",
        "ouvir sua música favorita em volume alto",
        "tirar um tempo para agradecer pelas conquistas",
        "celebrar com algo simbólico, como um doce ou um filme",
        "registrar esse bom momento em seu diário",
        "ligar para alguém querido e contar boas notícias",
        "criar algo artístico inspirado na sua felicidade",
        "dançar mesmo sem motivo",
        "organizar uma playlist animada",
        "praticar um hobby que lhe dá prazer",
        "relembrar memórias felizes com fotos",
        "assistir a uma comédia leve",
        "enviar uma mensagem positiva a alguém",
        "compartilhar um elogio com alguém",
        "fazer um gesto de gentileza",
        "começar um novo projeto com entusiasmo",
        "fazer um piquenique simples",
        "anotar 3 motivos para sorrir hoje",
        "comemorar com uma atividade diferente",
        "planejar um dia especial para si",
        "cantar no chuveiro sem se preocupar",
        "criar uma colagem de coisas que ama",
        "dar-se um pequeno presente simbólico",
        "inspirar outra pessoa com sua energia"
    ],

    "negativo": [
        "praticar a respiração consciente por alguns minutos",
        "falar com alguém em quem confia",
        "escrever o que está sentindo sem julgamentos",
        "tomar um banho relaxante",
        "evitar redes sociais por um tempo",
        "ouvir uma música calma e reconfortante",
        "descansar sem culpa",
        "fazer um exercício leve, como alongamento",
        "assistir a um vídeo reconfortante",
        "abraçar um travesseiro ou pelúcia",
        "criar uma lista de coisas boas que já superou",
        "ficar em silêncio e observar a respiração",
        "escrever uma carta que nunca será enviada",
        "tomar um chá quente lentamente",
        "evitar pensar no futuro e focar no presente",
        "cuidar de uma planta ou animal de estimação",
        "usar cores suaves ao seu redor",
        "acender uma vela perfumada",
        "dormir mais cedo esta noite",
        "procurar um ambiente calmo e seguro",
        "assistir a um filme reconfortante",
        "visualizar um lugar tranquilo",
        "desenhar ou rabiscar sem pressa",
        "organizar um pequeno espaço ao seu redor",
        "ler algo leve ou inspirador",
        "dar uma pausa real ao que está fazendo"
    ],

    "neutro": [
        "dar uma pequena caminhada e observar o ambiente",
        "ouvir uma música instrumental",
        "anotar o que está sentindo no momento",
        "experimentar desenhar algo simples",
        "tomar água com atenção plena",
        "refletir sobre pequenos detalhes do dia",
        "organizar algo em casa",
        "acender um incenso ou vela aromática",
        "escrever uma meta pequena para amanhã",
        "fazer um exercício de respiração curta",
        "observar o céu por alguns minutos",
        "ler uma página de um livro",
        "assistir a um vídeo curioso ou educativo",
        "observar uma planta de perto",
        "registrar um pensamento aleatório no diário",
        "movimentar o corpo por 5 minutos",
        "ficar um tempo sem celular",
        "ouvir um podcast leve",
        "explorar uma nova ideia criativa",
        "ficar em silêncio por alguns minutos",
        "brincar com um objeto sensorial",
        "tomar um banho em silêncio",
        "escrever uma lista de coisas neutras do dia",
        "fazer algo devagar e com atenção",
        "desenhar formas geométricas ou mandalas",
        "observar a própria respiração sem alterá-la"
    ]
}
